"""
Problem 2:

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.

https://projecteuler.net/problem=2
"""

def get_even_valued_fibonacci_sequence(limit):
    (first, second) = (1, 2)

    while second <= limit:
        if second % 2 == 0:
            yield second
        (first, second) = (second, first + second)

def run(limit):
    print('Sum of the even-valued fibonacci terms below ' + str(limit) + ':')
    print(sum(get_even_valued_fibonacci_sequence(limit)))    

if __name__ == '__main__':
    run(4000000)